Repository subsecretaria-tecnologia-nl/ciudadano-tramites, pull requests merged in 2021-07, with the labels that each got.

#416 change pressiotion to 5 from 3
  resources/js/app.js
  resources/js/components/ModalComponent.vue
Labels: Deploy to QA

#414 Fix/borrado ok
  package.json
  resources/js/app.js
  resources/js/components/ModalExpedientesComponent.vue
  resources/js/components/ResumenTramite5ISR.vue
  resources/js/components/TramiteComponent.vue
  resources/js/components/WizardComponent.vue
  resources/js/components/generales/BtnEliminarBorradorComponent.vue
  resources/js/components/generales/BtnGuardarTramiteComponent.vue
  resources/js/components/listadoTramites.vue
  resources/js/components/paginationComponent.vue
  resources/js/services/costosApi.services.js
Labels: Deploy QA

#423 show only file name
  app/Http/Controllers/ReferenceController.php
  resources/js/components/TramiteComponent.vue
  resources/js/components/listadoTramites.vue
  resources/js/components/paginationComponent.vue
  resources/sass/layout.scss
  routes/api.php
Labels: Deploy QA

#399 se esconde la ruta a usuarios. fix en el datatoogle de confirmar cont…
  resources/js/components/generales/CardPorfileComponent.vue
  resources/views/changePassword.blade.php
Labels: Deploy QA

#393 se elimina el boton de iniciar tramite que no se usaba
  resources/views/layout/base.blade.php
Labels: Deploy QA

#392 fix recovery password correo no registrado
  resources/js/recovery.js
Labels: Deploy QA

#421 move process to get file to watch on group and change file name instead url
  app/Http/Controllers/ReferenceController.php
  package.json
  resources/js/app.js
  resources/js/components/ModalExpedientesComponent.vue
  resources/js/components/ResumenTramite5ISR.vue
  resources/js/components/TramiteComponent.vue
  resources/js/components/WizardComponent.vue
  resources/js/components/generales/BtnEliminarBorradorComponent.vue
  resources/js/components/generales/BtnGuardarTramiteComponent.vue
  resources/js/components/generales/CardPorfileComponent.vue
  resources/js/components/listadoTramites.vue
  resources/js/components/paginationComponent.vue
  resources/js/recovery.js
  resources/js/services/costosApi.services.js
  resources/sass/layout.scss
  resources/views/changePassword.blade.php
  resources/views/layout/base.blade.php
  routes/api.php
Labels: Deploy Prod
