Repository subsecretaria-tecnologia-nl/ciudadano-tramites, pull requests merged in 2021-05, with the labels that each got.

#354 se esconde un div que estaba haciendo la tabla de enejanentes mas grande
  resources/js/app.js
  resources/js/components/EnajenantesComponente.vue
  resources/sass/layout.scss
  resources/views/layout/base.blade.php
Labels: bug

#371 New implementation of message event from insumos
  resources/js/app.js
  resources/js/components/tiposElementos/FirmaElectronicaComponent.vue
Labels: feature

#388 Fix/list permissions
  app/Http/Middleware/RolValidator.php
  resources/js/components/TramiteComponent.vue
  resources/js/components/paginationComponent.vue
Labels: Deploy to QA

#386 mostrar enajenantes en noraml y declaracion0
  resources/js/components/ResumenTramite5ISR.vue
  resources/js/components/tiposElementos/FileComponent.vue
Labels: Deploy to QA
